name: example
on: push
jobs:

    test-python-3-10:
        name: Check Python 3.10 on Ubuntu
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-python@v5
            with:
                python-version: "3.10"

          - name: Install package
            run: python -m pip install -e .[test]

          - name: Test package
            run: python -m pytest

    test-python-3-11:
        name: Check Python 3.11 on Ubuntu
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-python@v5
            with:
              python-version: "3.11"

          - name: Install package
            run: python -m pip install -e .[test]

          - name: Test package
            run: python -m pytest