name: example
on: push
jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
          - name: Greeting!
            run: echo "Hello, World!"

    test-python-3-10:
        name: Check Python 3.10 on Ubuntu
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-python@v5
            with:
                python-version: "3.10"

          - name: Install package
            run: python -m pip install -e .[test]

          - name: Test package
            run: python -m pytest