name: Releases

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SDist and Wheel
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*

  publish:
    needs: dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "build-artifacts"
          path: dist

      - name: Publish Release
        uses: pypa/gh-action-pypi-publish@v1.4.0
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: false