name: Releases

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SDist and Wheel
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "build-artifacts"
          path: dist

      - name: Publish Release
        run: echo "Uploading!"
